=== DarshanGitHub123/WebLabPractice/zFinalLabPractice/wp09/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstname" type="xs:string"/>
              
              <xs:element name="homeaddress">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="locality" type="xs:string"/>
                    <xs:element name="city" type="xs:string"/>
                    <xs:element name="pin" type="xs:string"/>
                    <xs:element name="country" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="phonenumber">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{10}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              
              <xs:element name="courses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="course" maxOccurs="3" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="title" type="xs:string"/>
                          <xs:element name="code" type="xs:string"/>
                          <xs:element name="marksScored">
                            <xs:simpleType>
                              <xs:restriction base="xs:integer">
                                <xs:minInclusive value="0"/>
                                <xs:maxInclusive value="100"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="passed" type="xs:boolean"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="usn" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DarshanGitHub123/WebLabPractice/zFinalLabPractice/wp09/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<students
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="C:\Users\darsh\Desktop\VI SEM\WT LAB\LABCODE\zFinalLabPractice\wp09\student.xsd">
    <student usn="1MS22CS001">
        <firstname>Rahul</firstname>
        <homeaddress>
            <locality>Rajajinagar</locality>
            <city>Bangalore</city>
            <pin>560010</pin>
            <country>India</country>
        </homeaddress>
        <phonenumber>9876543210</phonenumber>
        <courses>
            <course>
                <title>Data Structures</title>
                <code>CS201</code>
                <marksScored>85</marksScored>
                <passed>true</passed>
            </course>
            <course>
                <title>Operating Systems</title>
                <code>CS203</code>
                <marksScored>76</marksScored>
                <passed>true</passed>
            </course>
            <course>
                <title>Database Systems</title>
                <code>CS205</code>
                <marksScored>90</marksScored>
                <passed>true</passed>
            </course>
        </courses>
    </student>

    <student usn="1MS22CS002">
        <firstname>Anjali</firstname>
        <homeaddress>
            <locality>MG Road</locality>
            <city>Mysore</city>
            <pin>570001</pin>
            <country>India</country>
        </homeaddress>
        <phonenumber>9123456789</phonenumber>
        <courses>
            <course>
                <title>Computer Networks</title>
                <code>CS209</code>
                <marksScored>82</marksScored>
                <passed>true</passed>
            </course>
			<course>
                <title>Computer Networks</title>
                <code>CS209</code>
                <marksScored>82</marksScored>
                <passed>true</passed>
            </course>
			
			
			<course>
                <title>Computer Networks</title>
                <code>CS209</code>
                <marksScored>82</marksScored>
                <passed>true</passed>
            </course>
			
        </courses>
		
    </student>
</students>
