=== DarshanGitHub123/WebLabPractice/XML/XML practice/cars/cars.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="car_catalog">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="car" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="make" type="xsd:string"/>
              <xsd:element name="model" type="xsd:string"/>
              <xsd:element name="year">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                    <xsd:minInclusive value="1900"/>
                    <xsd:maxInclusive value="2099"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="color" type="xsd:string"/>
              <xsd:element name="engine">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="number_of_cylinders">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:integer">
                          <xsd:minInclusive value="2"/>
                          <xsd:maxInclusive value="16"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="fuel_system">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:maxLength value="30"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="number_of_doors" type="xsd:string"/>
              <xsd:element name="transmission_type" type="xsd:string"/>
              <xsd:element name="accessories">
                <xsd:complexType>
                  <xsd:attribute name="radio" type="xsd:string" use="required"/>
                  <xsd:attribute name="air_conditioning" type="xsd:string" use="required"/>
                  <xsd:attribute name="power_windows" type="xsd:string" use="required"/>
                  <xsd:attribute name="power_steering" type="xsd:string" use="required"/>
                  <xsd:attribute name="power_breaks" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== DarshanGitHub123/WebLabPractice/XML/XML practice/cars/carCatalog.xml
<?xml version="1.0"?>
<car_catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="cars.xsd">

    <car>
        <make>Chevrolet</make>
        <model>Impala</model>
        <year>1997</year>
        <color>Light Blue</color>
        <engine>
            <number_of_cylinders>8</number_of_cylinders>
            <fuel_system>multi-port fuel injected</fuel_system>
        </engine>
        <number_of_doors>4</number_of_doors>
        <transmission_type>4 speed automatic</transmission_type>
        <accessories radio="yes" air_conditioning="yes" power_windows="yes"
                     power_steering="yes" power_breaks="yes"/>
    </car>

    <car>
        <make>Toyota</make>
        <model>Camry</model>
        <year>1985</year>
        <color>Blue</color>
        <engine>
            <number_of_cylinders>8</number_of_cylinders>
            <fuel_system>multi-port fuel injected</fuel_system>
        </engine>
        <number_of_doors>4</number_of_doors>
        <transmission_type>4 speed automatic</transmission_type>
        <accessories radio="yes" air_conditioning="yes" power_windows="yes"
                     power_steering="yes" power_breaks="yes"/>
    </car>

</car_catalog>
